version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todos
  app:
    image: back-cortex
    ports:
      - "13000:3000"
